config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'users#index'
  resources :admins do
    collection do
      get "admission"
      post "create_student_and_guardian"
      get "level_load"
      get "year_load"
      get "semester_load"
      get "shift_load"
      get "student_profile/:id" , action: "student_profile", as: :student_profile
      get "student_list"
      get "student_search"
      get "show_student_according_to_class"
      get "student_count"
      get "student_count_class_wise/:id", action: 'student_count_class_wise', as: :student_count_class_wise
      get "show_students_according_to_gender"
      get "search_students_according_to_gender"
      get "fee_setting"
      post "fee_create"
      get "nothing_found"
    end

  end

  resources :students do
    collection do
      get 'student_profile'
    end
  end

  resources :teachers
  resources :guardians
  resources :fees do
    collection do
      get 'load_class_wise_fees'
      get "fee_collect/:id", action: 'fee_collect', as: :fee_collect
      get "fee_collect_statistics"
      post "student_current_account"
      get 'fee'
    end
  end

end

app/models/account_year.rb
class AccountYear < ActiveRecord::Base
  validates :name, :uniqueness => { :case_sensitive => false }
  validates :name, presence: true
  has_many :fees

end

app/models/additional_fee.rb
class AdditionalFee < ActiveRecord::Base
  belongs_to :fee
  validates :name, presence:true
end

app/models/campus.rb
class Campus < ActiveRecord::Base
  has_many :students
  validates :name, presence: true
end

app/models/fee.rb
class Fee < ActiveRecord::Base
  belongs_to :level
  belongs_to :month
  belongs_to :account_year
  has_many :additional_fees

  validates :level_id, :month_id, :account_year_id, :last_date_fee, presence: true
  validates :monthly_fee, :session_fee, :ict_fee, :admission_fee,:exam_fee, :others, numericality: {greater_than_or_equal_to: 0}
end

app/models/guardian.rb
class Guardian < ActiveRecord::Base
  belongs_to :user
  has_one :student
end

app/models/level.rb
class Level < ActiveRecord::Base

  validates :name, :uniqueness => { :case_sensitive => false }
  #Level means class
  has_many :years
  has_many :students
  has_many :fees

end

app/models/month.rb
class Month < ActiveRecord::Base
  validates :name, :uniqueness => { :case_sensitive => false }
  has_many :fees
end

app/models/semester.rb
class Semester < ActiveRecord::Base

  belongs_to :year
  has_many :shifts

end

app/models/shift.rb
class Shift < ActiveRecord::Base

  belongs_to :semester
  has_and_belongs_to_many :students

end

app/models/student.rb
class Student < ActiveRecord::Base
  mount_uploader :profilepic, ProfilepicUploader
  mount_uploader :coverpic, ProfilepicUploader
  belongs_to :user
  belongs_to :guardian
  belongs_to :campus
  has_and_belongs_to_many :shifts
  belongs_to :level
  has_one :student_fee, :dependent => :destroy
  has_many :student_pay_reports, :dependent => :destroy
end

app/models/student_fee.rb
class StudentFee < ActiveRecord::Base
  belongs_to :student
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # validates :name, presence: true
  validates :user_name, presence: true
  # validates :user_name, presence: true
  # validates :user_flag, presence: true, numericality: true



  mount_uploader :profilepic, ProfilepicUploader


  # has_and_belongs_to_many :shifts
  has_many :guardians
  has_many :students


  def email_required?
    false
  end

  def email_changed?
    false
  end

end

app/models/year.rb
class Year < ActiveRecord::Base

  belongs_to :level
  has_many :semesters

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/fees_helper.rb
module FeesHelper
end

app/helpers/fess_helper.rb
module FessHelper
end

app/helpers/guardians_helper.rb
module GuardiansHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/_search_students_according_to_gender_partial_view.html.erb
<% if @stdnt.respond_to?('each') %>
        <% @stdnt.each do |std| %>
            <tr>
              <td><%= std.user.user_name %></td>
              <td><a href="mailto:#"><%= link_to std.first_name+' '+ std.last_name, student_profile_admins_path(std.user.id) %></a></td>
              <td>10</td>
              <td><%= std.level.name %> </td>
              <td>Science</td>
              <td>2015</td>
              <td>Fall-2015</td>
              <td><span class="label label-primary"><%= std.gender %></span></td>
              <td><%= std.guardian.contact_number %></td>
              <td><span class="label label-success">paid</span></td>
              <td>
                <div class="btn-group btn-group-xs">
                  <a data-toggle="tooltip" title="Off" class="btn btn-default"><i class="fa fa-power-off"></i></a>
                  <a data-toggle="tooltip" title="View" class="btn btn-default"><i class="fa fa-edit"></i></a>
                </div>
              </td>
            </tr>
        <% end %>
<% else %>
    <% if @stdnt %>
        <tr>
          <td><%= @stdnt.user.user_name %></td>
          <td><a href="mailto:#"><%= link_to @stdnt.first_name+' '+ @stdnt.last_name, student_profile_admins_path(@stdnt.user.id) %></a></td>
          <td>10</td>
          <td><%= @stdnt.level.name %> </td>
          <td>Science</td>
          <td>2015</td>
          <td>Fall-2015</td>
          <td><span class="label label-primary"><%= @stdnt.gender %></span></td>
          <td><%= @stdnt.guardian.contact_number %></td>
          <td><span class="label label-success">paid</span></td>
          <td>
            <div class="btn-group btn-group-xs">
              <a data-toggle="tooltip" title="Off" class="btn btn-default"><i class="fa fa-power-off"></i></a>
              <a data-toggle="tooltip" title="View" class="btn btn-default"><i class="fa fa-edit"></i></a>
            </div>
          </td>
        </tr>
    <% else %>
        <tr>
          <td colspan="100%" style="width:100%">
            <h4 style="text-align: center">This id is not available</h4>
          </td>
        </tr>
    <% end %>
<% end %>

app/views/admins/_show_student_according_to_class_partial_view.html.erb
<% @all_students_AC.each do |st| %>
    <div class="col-sm-6">
      <div class="widget border-student">
        <div class="widget-content">
          <div class="student-list">
            <%= image_tag(st.profilepic,:class => 'img-responsive') if st.profilepic %>
          </div>
          <div class="student-details">
            <small class="text-left">
              <h4><b><%= link_to  st.first_name+' '+st.last_name, student_profile_admins_path(st.user.id)%></b></h4>
              <p><strong>User Id :<%= st.user.id %></strong></p>
              <p><strong>User name :<%= st.user.user_name %></strong></p>
              <p><b> Class: <%= st.shifts.first.semester.year.level.name unless st.shifts.first.nil? %> , Roll : <%= st.id %> </b></p>
            </small>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/admins/_student_search_partial_view.html.erb
   <% if @stdnt %>
      <div class="widget border-student">
        <div class="widget-content">
          <div class="student-list">
            <%= image_tag(@stdnt.profilepic,:class => 'img-responsive') %>
          </div>
          <div class="student-details">
            <small class="text-left">
              <h4><b><%= link_to  @stdnt.first_name+' '+@stdnt.last_name, student_profile_admins_path(@stdnt.user.id)%></b></h4>
              <p><strong>User Id :<%= @stdnt.user.id %></strong></p>
              <p><strong>User name :<%= @stdnt.user.user_name %></strong></p>
              <p><b> Class: <%= @stdnt.shifts.first.semester.year.level.name unless @stdnt.shifts.first.nil? %> , Roll : <%= @stdnt.id %> </b></p>
            </small>
          </div>
        </div>
      </div>
<% end %>

app/views/admins/_years_load_dropdown.html.erb
<p>
  <%= :Years %>
  <%= select_tag :select_year,  options_from_collection_for_select(@years, :id, :name) %>
</p>

app/views/admins/nothing_found.html.erb
<div class="content ">
  <!-- Start info box -->
  <div class="md-modal md-3d-flip-vertical" id="task-progress">
    <div class="md-content">
      <h3><strong>Task Progress</strong> Information</h3>
      <div>
        <p>CLEANING BUGS</p>
        <div class="progress progress-xs for-modal">
          <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
            <span class="sr-only">80&#37; Complete</span>
          </div>
        </div>
        <p>POSTING SOME STUFF</p>
        <div class="progress progress-xs for-modal">
          <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 65%">
            <span class="sr-only">65&#37; Complete</span>
          </div>
        </div>
        <p>BACKUP DATA FROM SERVER</p>
        <div class="progress progress-xs for-modal">
          <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 95%">
            <span class="sr-only">95&#37; Complete</span>
          </div>
        </div>
        <p>RE-DESIGNING WEB APPLICATION</p>
        <div class="progress progress-xs for-modal">
          <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
            <span class="sr-only">100&#37; Complete</span>
          </div>
        </div>
        <p class="text-center">
          <button class="btn btn-danger btn-sm md-close">Close</button>
        </p>
      </div>
    </div>
  </div>

  <!-- Modal Logout -->


  <!-- Begin page -->
  <div class="container">
    <div class="full-content-center animated flipInX">
      <h1 style="font-weight:100; color:#757575;">404</h1>
      <h2>The page you are looking for is definitely not this!</h2><br>
      <p class="text-lightblue-2">You better try our awesome search:</p>
      <div class="row">
        <div class="icon-added input-group col-sm-8 col-sm-offset-2">
          <i class="fa fa-search"></i>
          <input type="text" class="form-control">
					<span class="input-group-btn">
				        <button class="btn btn-success" type="button">Search</button>
				      </span>
        </div>
      </div><br>
      <%= link_to admins_path, :class=> 'btn btn-primary btn-sm' do %>
          <i class="fa fa-angle-left"></i> Back to Dashboard
      <% end %>
    </div>
      </div>
    </div>

app/views/admins/search_students_according_to_gender.js.erb
$('.students_container table tbody').html('<%= escape_javascript render("admins/search_students_according_to_gender_partial_view") %>');

app/views/admins/semester_load.js.erb
<% if @semesters.any? %>
$('#select_semester').html('<%= escape_javascript options_from_collection_for_select(@semesters,:id,:name) %>')
<% end %>

app/views/admins/shift_load.js.erb
<% if @shifts.any? %>
$('#select_shift').html('<%= escape_javascript options_from_collection_for_select(@shifts,:id,:name) %>')
<% end %>

app/views/admins/show_student_according_to_class.js.erb
$('.students_container').html('<%= escape_javascript render("admins/show_student_according_to_class_partial_view") %>')

app/views/admins/student_count.js.erb
$('.students_container').html('<%= escape_javascript render("admins/student_count_partial_view") %>')

app/views/admins/year_load.js.erb
<% if @years.any? %>
$('#select_year').html('<%= escape_javascript options_from_collection_for_select(@years,:id,:name) %>')
<% end %>

app/views/layouts/404.html.erb
<h1>
  No Record Found
</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Educationapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>
<body>
<% if notice %>
    <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>

</body>
</html>

app/views/layouts/student_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Educationapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if notice %>
    <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
<% end %>
jaskldj lksadjlksajdlkasjdlkajsd

<%= yield %>

</body>
</html>